class CountryCode {
  const CountryCode({
    required this.name,
    required this.dialCode,
    required this.code,
    required this.flag,
    this.minLength = 10,
    this.maxLength = 10,
  });

  final String name;
  final String dialCode;
  final String code;
  final String flag;
  final int minLength;
  final int maxLength;

  String get displayDialCode => '+$dialCode';

  static const List<CountryCode> all = [
    CountryCode(name: 'Türkiye', dialCode: '90', code: 'TR', flag: '🇹🇷'),
    CountryCode(
        name: 'United States',
        dialCode: '1',
        code: 'US',
        flag: '🇺🇸',
        minLength: 10,
        maxLength: 10),
    CountryCode(
        name: 'United Kingdom',
        dialCode: '44',
        code: 'GB',
        flag: '🇬🇧',
        minLength: 10,
        maxLength: 10),
    CountryCode(
        name: 'Germany',
        dialCode: '49',
        code: 'DE',
        flag: '🇩🇪',
        minLength: 10,
        maxLength: 11),
    CountryCode(
        name: 'France',
        dialCode: '33',
        code: 'FR',
        flag: '🇫🇷',
        minLength: 9,
        maxLength: 9),
    CountryCode(
        name: 'Italy',
        dialCode: '39',
        code: 'IT',
        flag: '🇮🇹',
        minLength: 9,
        maxLength: 10),
    CountryCode(
        name: 'Spain',
        dialCode: '34',
        code: 'ES',
        flag: '🇪🇸',
        minLength: 9,
        maxLength: 9),
    CountryCode(
        name: 'Netherlands',
        dialCode: '31',
        code: 'NL',
        flag: '🇳🇱',
        minLength: 9,
        maxLength: 9),
    CountryCode(
        name: 'Belgium',
        dialCode: '32',
        code: 'BE',
        flag: '🇧🇪',
        minLength: 9,
        maxLength: 9),
    CountryCode(
        name: 'Austria',
        dialCode: '43',
        code: 'AT',
        flag: '🇦🇹',
        minLength: 10,
        maxLength: 11),
    CountryCode(
        name: 'Switzerland',
        dialCode: '41',
        code: 'CH',
        flag: '🇨🇭',
        minLength: 9,
        maxLength: 9),
    CountryCode(
        name: 'Sweden',
        dialCode: '46',
        code: 'SE',
        flag: '🇸🇪',
        minLength: 9,
        maxLength: 9),
    CountryCode(
        name: 'Norway',
        dialCode: '47',
        code: 'NO',
        flag: '🇳🇴',
        minLength: 8,
        maxLength: 8),
    CountryCode(
        name: 'Denmark',
        dialCode: '45',
        code: 'DK',
        flag: '🇩🇰',
        minLength: 8,
        maxLength: 8),
    CountryCode(
        name: 'Finland',
        dialCode: '358',
        code: 'FI',
        flag: '🇫🇮',
        minLength: 9,
        maxLength: 10),
    CountryCode(
        name: 'Poland',
        dialCode: '48',
        code: 'PL',
        flag: '🇵🇱',
        minLength: 9,
        maxLength: 9),
    CountryCode(
        name: 'Czech Republic',
        dialCode: '420',
        code: 'CZ',
        flag: '🇨🇿',
        minLength: 9,
        maxLength: 9),
    CountryCode(
        name: 'Romania',
        dialCode: '40',
        code: 'RO',
        flag: '🇷🇴',
        minLength: 9,
        maxLength: 9),
    CountryCode(
        name: 'Hungary',
        dialCode: '36',
        code: 'HU',
        flag: '🇭🇺',
        minLength: 9,
        maxLength: 9),
    CountryCode(
        name: 'Greece',
        dialCode: '30',
        code: 'GR',
        flag: '🇬🇷',
        minLength: 10,
        maxLength: 10),
    CountryCode(
        name: 'Portugal',
        dialCode: '351',
        code: 'PT',
        flag: '🇵🇹',
        minLength: 9,
        maxLength: 9),
    CountryCode(
        name: 'Ireland',
        dialCode: '353',
        code: 'IE',
        flag: '🇮🇪',
        minLength: 9,
        maxLength: 9),
    CountryCode(
        name: 'Russia',
        dialCode: '7',
        code: 'RU',
        flag: '🇷🇺',
        minLength: 10,
        maxLength: 10),
    CountryCode(
        name: 'Ukraine',
        dialCode: '380',
        code: 'UA',
        flag: '🇺🇦',
        minLength: 9,
        maxLength: 9),
    CountryCode(
        name: 'Azerbaijan',
        dialCode: '994',
        code: 'AZ',
        flag: '🇦🇿',
        minLength: 9,
        maxLength: 9),
    CountryCode(
        name: 'Georgia',
        dialCode: '995',
        code: 'GE',
        flag: '🇬🇪',
        minLength: 9,
        maxLength: 9),
    CountryCode(
        name: 'Kazakhstan',
        dialCode: '7',
        code: 'KZ',
        flag: '🇰🇿',
        minLength: 10,
        maxLength: 10),
    CountryCode(
        name: 'Uzbekistan',
        dialCode: '998',
        code: 'UZ',
        flag: '🇺🇿',
        minLength: 9,
        maxLength: 9),
    CountryCode(
        name: 'Japan',
        dialCode: '81',
        code: 'JP',
        flag: '🇯🇵',
        minLength: 10,
        maxLength: 11),
    CountryCode(
        name: 'South Korea',
        dialCode: '82',
        code: 'KR',
        flag: '🇰🇷',
        minLength: 10,
        maxLength: 11),
    CountryCode(
        name: 'China',
        dialCode: '86',
        code: 'CN',
        flag: '🇨🇳',
        minLength: 11,
        maxLength: 11),
    CountryCode(
        name: 'India',
        dialCode: '91',
        code: 'IN',
        flag: '🇮🇳',
        minLength: 10,
        maxLength: 10),
    CountryCode(
        name: 'Pakistan',
        dialCode: '92',
        code: 'PK',
        flag: '🇵🇰',
        minLength: 10,
        maxLength: 10),
    CountryCode(
        name: 'Saudi Arabia',
        dialCode: '966',
        code: 'SA',
        flag: '🇸🇦',
        minLength: 9,
        maxLength: 9),
    CountryCode(
        name: 'UAE',
        dialCode: '971',
        code: 'AE',
        flag: '🇦🇪',
        minLength: 9,
        maxLength: 9),
    CountryCode(
        name: 'Egypt',
        dialCode: '20',
        code: 'EG',
        flag: '🇪🇬',
        minLength: 10,
        maxLength: 10),
    CountryCode(
        name: 'Brazil',
        dialCode: '55',
        code: 'BR',
        flag: '🇧🇷',
        minLength: 10,
        maxLength: 11),
    CountryCode(
        name: 'Mexico',
        dialCode: '52',
        code: 'MX',
        flag: '🇲🇽',
        minLength: 10,
        maxLength: 10),
    CountryCode(
        name: 'Argentina',
        dialCode: '54',
        code: 'AR',
        flag: '🇦🇷',
        minLength: 10,
        maxLength: 10),
    CountryCode(
        name: 'Canada',
        dialCode: '1',
        code: 'CA',
        flag: '🇨🇦',
        minLength: 10,
        maxLength: 10),
    CountryCode(
        name: 'Australia',
        dialCode: '61',
        code: 'AU',
        flag: '🇦🇺',
        minLength: 9,
        maxLength: 9),
    CountryCode(
        name: 'New Zealand',
        dialCode: '64',
        code: 'NZ',
        flag: '🇳🇿',
        minLength: 9,
        maxLength: 10),
    CountryCode(
        name: 'South Africa',
        dialCode: '27',
        code: 'ZA',
        flag: '🇿🇦',
        minLength: 9,
        maxLength: 9),
    CountryCode(
        name: 'Nigeria',
        dialCode: '234',
        code: 'NG',
        flag: '🇳🇬',
        minLength: 10,
        maxLength: 10),
    CountryCode(
        name: 'Israel',
        dialCode: '972',
        code: 'IL',
        flag: '🇮🇱',
        minLength: 9,
        maxLength: 9),
    CountryCode(
        name: 'Iraq',
        dialCode: '964',
        code: 'IQ',
        flag: '🇮🇶',
        minLength: 10,
        maxLength: 10),
    CountryCode(
        name: 'Iran',
        dialCode: '98',
        code: 'IR',
        flag: '🇮🇷',
        minLength: 10,
        maxLength: 10),
    CountryCode(
        name: 'Bulgaria',
        dialCode: '359',
        code: 'BG',
        flag: '🇧🇬',
        minLength: 9,
        maxLength: 9),
    CountryCode(
        name: 'Serbia',
        dialCode: '381',
        code: 'RS',
        flag: '🇷🇸',
        minLength: 9,
        maxLength: 10),
    CountryCode(
        name: 'Croatia',
        dialCode: '385',
        code: 'HR',
        flag: '🇭🇷',
        minLength: 9,
        maxLength: 9),
    CountryCode(
        name: 'KKTC',
        dialCode: '90392',
        code: 'CY',
        flag: '🇨🇾',
        minLength: 7,
        maxLength: 7),
  ];

  static CountryCode get turkey => all.firstWhere((c) => c.code == 'TR');
}
